// Supabase Database Types
// Auto-generated by `supabase gen types typescript --linked > src/lib/supabase/types.ts`
// Re-run after any schema migration to keep types in sync.
//
// Until `supabase gen types` is run, this file provides manual type definitions
// that mirror the schema in supabase/migrations/.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          name: string | null;
          avatar_url: string | null;
          role: "customer" | "admin" | "super_admin";
          phone: string | null;
          email_verified_at: string | null;
          last_sign_in_at: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id: string;
          email: string;
          name?: string | null;
          avatar_url?: string | null;
          role?: "customer" | "admin" | "super_admin";
          phone?: string | null;
          email_verified_at?: string | null;
          last_sign_in_at?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          name?: string | null;
          avatar_url?: string | null;
          role?: "customer" | "admin" | "super_admin";
          phone?: string | null;
          email_verified_at?: string | null;
          last_sign_in_at?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      admin_users: {
        Row: {
          id: string;
          user_id: string;
          role: "admin" | "super_admin";
          permissions: Json | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          role?: "admin" | "super_admin";
          permissions?: Json | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          role?: "admin" | "super_admin";
          permissions?: Json | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [{ foreignKeyName: "admin_users_user_id_fkey"; columns: ["user_id"]; referencedRelation: "users"; referencedColumns: ["id"] }];
      };
      addresses: {
        Row: {
          id: string;
          user_id: string;
          type: "shipping" | "billing";
          line1: string;
          line2: string | null;
          city: string;
          state: string | null;
          postal_code: string;
          country: string;
          is_default: boolean;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          type?: "shipping" | "billing";
          line1: string;
          line2?: string | null;
          city: string;
          state?: string | null;
          postal_code: string;
          country?: string;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: "shipping" | "billing";
          line1?: string;
          line2?: string | null;
          city?: string;
          state?: string | null;
          postal_code?: string;
          country?: string;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [{ foreignKeyName: "addresses_user_id_fkey"; columns: ["user_id"]; referencedRelation: "users"; referencedColumns: ["id"] }];
      };
      destinations: {
        Row: {
          id: string;
          slug: string;
          name: string;
          region: string | null;
          country: string;
          tagline: string | null;
          mood: string | null;
          palette_bg: string | null;
          palette_ink: string | null;
          palette_accent: string | null;
          hero_url: string | null;
          cover_url: string | null;
          season: string | null;
          category: "Coastline" | "Mountains" | "Cities" | "Deserts" | "Backwaters" | "Atlantic";
          published: boolean;
          sort_order: number;
          stories: Json;
          gallery: Json;
          pairings: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          region?: string | null;
          country?: string;
          tagline?: string | null;
          mood?: string | null;
          palette_bg?: string | null;
          palette_ink?: string | null;
          palette_accent?: string | null;
          hero_url?: string | null;
          cover_url?: string | null;
          season?: string | null;
          category: "Coastline" | "Mountains" | "Cities" | "Deserts" | "Backwaters" | "Atlantic";
          published?: boolean;
          sort_order?: number;
          stories?: Json;
          gallery?: Json;
          pairings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          region?: string | null;
          country?: string;
          tagline?: string | null;
          mood?: string | null;
          palette_bg?: string | null;
          palette_ink?: string | null;
          palette_accent?: string | null;
          hero_url?: string | null;
          cover_url?: string | null;
          season?: string | null;
          category?: "Coastline" | "Mountains" | "Cities" | "Deserts" | "Backwaters" | "Atlantic";
          published?: boolean;
          sort_order?: number;
          stories?: Json;
          gallery?: Json;
          pairings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      book_editions: {
        Row: {
          id: string;
          slug: string;
          name: string;
          pages_min: number;
          pages_max: number;
          size_label: string;
          base_price: number;
          ideal_for: string | null;
          photo_estimate_min: number | null;
          photo_estimate_max: number | null;
          description: string | null;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          pages_min: number;
          pages_max: number;
          size_label: string;
          base_price: number;
          ideal_for?: string | null;
          photo_estimate_min?: number | null;
          photo_estimate_max?: number | null;
          description?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          pages_min?: number;
          pages_max?: number;
          size_label?: string;
          base_price?: number;
          ideal_for?: string | null;
          photo_estimate_min?: number | null;
          photo_estimate_max?: number | null;
          description?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      cover_designs: {
        Row: {
          id: string;
          slug: string;
          name: string;
          mood: string | null;
          ink_color: string | null;
          panel_color: string | null;
          image_url: string | null;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          mood?: string | null;
          ink_color?: string | null;
          panel_color?: string | null;
          image_url?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          mood?: string | null;
          ink_color?: string | null;
          panel_color?: string | null;
          image_url?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      destination_cover_designs: {
        Row: {
          destination_id: string;
          cover_design_id: string;
          sort_order: number;
        };
        Insert: {
          destination_id: string;
          cover_design_id: string;
          sort_order?: number;
        };
        Update: {
          destination_id?: string;
          cover_design_id?: string;
          sort_order?: number;
        };
        Relationships: [
          { foreignKeyName: "destination_cover_designs_destination_id_fkey"; columns: ["destination_id"]; referencedRelation: "destinations"; referencedColumns: ["id"] },
          { foreignKeyName: "destination_cover_designs_cover_design_id_fkey"; columns: ["cover_design_id"]; referencedRelation: "cover_designs"; referencedColumns: ["id"] },
        ];
      };
      book_materials: {
        Row: {
          id: string;
          slug: string;
          name: string;
          feel: string | null;
          description: string | null;
          price_delta: number;
          swatch_color: string | null;
          texture_url: string | null;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          feel?: string | null;
          description?: string | null;
          price_delta?: number;
          swatch_color?: string | null;
          texture_url?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          feel?: string | null;
          description?: string | null;
          price_delta?: number;
          swatch_color?: string | null;
          texture_url?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      paper_types: {
        Row: {
          id: string;
          slug: string;
          name: string;
          weight: string | null;
          finish: string | null;
          best_for: string | null;
          price_delta: number;
          texture_url: string | null;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          weight?: string | null;
          finish?: string | null;
          best_for?: string | null;
          price_delta?: number;
          texture_url?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          weight?: string | null;
          finish?: string | null;
          best_for?: string | null;
          price_delta?: number;
          texture_url?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      page_counts: {
        Row: {
          id: string;
          pages: number;
          label: string;
          recommended_min: number | null;
          recommended_max: number | null;
          ideal_for: string | null;
          price_delta: number;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          pages: number;
          label: string;
          recommended_min?: number | null;
          recommended_max?: number | null;
          ideal_for?: string | null;
          price_delta?: number;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          pages?: number;
          label?: string;
          recommended_min?: number | null;
          recommended_max?: number | null;
          ideal_for?: string | null;
          price_delta?: number;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      books: {
        Row: {
          id: string;
          user_id: string;
          destination_id: string | null;
          edition_id: string | null;
          cover_design_id: string | null;
          material_id: string | null;
          paper_type_id: string | null;
          page_count_id: string | null;
          title: string | null;
          status: "draft" | "uploading" | "generating" | "preview_ready" | "ordered" | "printing" | "quality_check" | "packed" | "shipped" | "delivered" | "archived";
          extras: Json;
          price_breakdown: Json | null;
          total_price: number | null;
          photo_count: number;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          destination_id?: string | null;
          edition_id?: string | null;
          cover_design_id?: string | null;
          material_id?: string | null;
          paper_type_id?: string | null;
          page_count_id?: string | null;
          title?: string | null;
          status?: "draft" | "uploading" | "generating" | "preview_ready" | "ordered" | "printing" | "quality_check" | "packed" | "shipped" | "delivered" | "archived";
          extras?: Json;
          price_breakdown?: Json | null;
          total_price?: number | null;
          photo_count?: number;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          destination_id?: string | null;
          edition_id?: string | null;
          cover_design_id?: string | null;
          material_id?: string | null;
          paper_type_id?: string | null;
          page_count_id?: string | null;
          title?: string | null;
          status?: "draft" | "uploading" | "generating" | "preview_ready" | "ordered" | "printing" | "quality_check" | "packed" | "shipped" | "delivered" | "archived";
          extras?: Json;
          price_breakdown?: Json | null;
          total_price?: number | null;
          photo_count?: number;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: "books_user_id_fkey"; columns: ["user_id"]; referencedRelation: "users"; referencedColumns: ["id"] },
          { foreignKeyName: "books_destination_id_fkey"; columns: ["destination_id"]; referencedRelation: "destinations"; referencedColumns: ["id"] },
          { foreignKeyName: "books_edition_id_fkey"; columns: ["edition_id"]; referencedRelation: "book_editions"; referencedColumns: ["id"] },
          { foreignKeyName: "books_cover_design_id_fkey"; columns: ["cover_design_id"]; referencedRelation: "cover_designs"; referencedColumns: ["id"] },
          { foreignKeyName: "books_material_id_fkey"; columns: ["material_id"]; referencedRelation: "book_materials"; referencedColumns: ["id"] },
          { foreignKeyName: "books_paper_type_id_fkey"; columns: ["paper_type_id"]; referencedRelation: "paper_types"; referencedColumns: ["id"] },
          { foreignKeyName: "books_page_count_id_fkey"; columns: ["page_count_id"]; referencedRelation: "page_counts"; referencedColumns: ["id"] },
        ];
      };
      book_photos: {
        Row: {
          id: string;
          book_id: string;
          storage_url: string;
          thumbnail_url: string | null;
          sort_order: number;
          width: number | null;
          height: number | null;
          file_size_bytes: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          book_id: string;
          storage_url: string;
          thumbnail_url?: string | null;
          sort_order?: number;
          width?: number | null;
          height?: number | null;
          file_size_bytes?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          book_id?: string;
          storage_url?: string;
          thumbnail_url?: string | null;
          sort_order?: number;
          width?: number | null;
          height?: number | null;
          file_size_bytes?: number | null;
          created_at?: string;
        };
        Relationships: [{ foreignKeyName: "book_photos_book_id_fkey"; columns: ["book_id"]; referencedRelation: "books"; referencedColumns: ["id"] }];
      };
      orders: {
        Row: {
          id: string;
          user_id: string;
          address_id: string;
          order_number: string;
          status: "pending" | "confirmed" | "processing" | "shipped" | "delivered" | "cancelled" | "refunded";
          subtotal: number;
          shipping_cost: number;
          total: number;
          currency: string;
          notes: string | null;
          paid_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          address_id: string;
          order_number: string;
          status?: "pending" | "confirmed" | "processing" | "shipped" | "delivered" | "cancelled" | "refunded";
          subtotal: number;
          shipping_cost?: number;
          total: number;
          currency?: string;
          notes?: string | null;
          paid_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          address_id?: string;
          order_number?: string;
          status?: "pending" | "confirmed" | "processing" | "shipped" | "delivered" | "cancelled" | "refunded";
          subtotal?: number;
          shipping_cost?: number;
          total?: number;
          currency?: string;
          notes?: string | null;
          paid_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "orders_user_id_fkey"; columns: ["user_id"]; referencedRelation: "users"; referencedColumns: ["id"] },
          { foreignKeyName: "orders_address_id_fkey"; columns: ["address_id"]; referencedRelation: "addresses"; referencedColumns: ["id"] },
        ];
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          book_id: string | null;
          item_type: string;
          name: string;
          quantity: number;
          unit_price: number;
          total_price: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          book_id?: string | null;
          item_type: string;
          name: string;
          quantity?: number;
          unit_price: number;
          total_price: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string;
          book_id?: string | null;
          item_type?: string;
          name?: string;
          quantity?: number;
          unit_price?: number;
          total_price?: number;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "order_items_order_id_fkey"; columns: ["order_id"]; referencedRelation: "orders"; referencedColumns: ["id"] },
          { foreignKeyName: "order_items_book_id_fkey"; columns: ["book_id"]; referencedRelation: "books"; referencedColumns: ["id"] },
        ];
      };
      jobs: {
        Row: {
          id: string;
          type: "upload_images" | "generate_preview" | "generate_pdf" | "send_email" | "generate_thumbnail" | "sync_order";
          status: "pending" | "processing" | "completed" | "failed" | "cancelled";
          payload: Json;
          result: Json | null;
          error_message: string | null;
          attempts: number;
          max_attempts: number;
          scheduled_for: string | null;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          type: "upload_images" | "generate_preview" | "generate_pdf" | "send_email" | "generate_thumbnail" | "sync_order";
          status?: "pending" | "processing" | "completed" | "failed" | "cancelled";
          payload?: Json;
          result?: Json | null;
          error_message?: string | null;
          attempts?: number;
          max_attempts?: number;
          scheduled_for?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          type?: "upload_images" | "generate_preview" | "generate_pdf" | "send_email" | "generate_thumbnail" | "sync_order";
          status?: "pending" | "processing" | "completed" | "failed" | "cancelled";
          payload?: Json;
          result?: Json | null;
          error_message?: string | null;
          attempts?: number;
          max_attempts?: number;
          scheduled_for?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: "order_confirmation" | "shipping_update" | "delivery_confirmation" | "promotional" | "job_failed";
          channel: "email" | "in_app";
          subject: string;
          body: string;
          data: Json | null;
          read_at: string | null;
          sent_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: "order_confirmation" | "shipping_update" | "delivery_confirmation" | "promotional" | "job_failed";
          channel: "email" | "in_app";
          subject: string;
          body: string;
          data?: Json | null;
          read_at?: string | null;
          sent_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: "order_confirmation" | "shipping_update" | "delivery_confirmation" | "promotional" | "job_failed";
          channel?: "email" | "in_app";
          subject?: string;
          body?: string;
          data?: Json | null;
          read_at?: string | null;
          sent_at?: string | null;
          created_at?: string;
        };
        Relationships: [{ foreignKeyName: "notifications_user_id_fkey"; columns: ["user_id"]; referencedRelation: "users"; referencedColumns: ["id"] }];
      };
      coupons: {
        Row: {
          id: string;
          code: string;
          discount_type: "percentage" | "fixed_amount";
          discount_value: number;
          min_order_amount: number | null;
          max_uses: number | null;
          used_count: number;
          max_uses_per_user: number | null;
          is_active: boolean;
          expires_at: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          code: string;
          discount_type: "percentage" | "fixed_amount";
          discount_value: number;
          min_order_amount?: number | null;
          max_uses?: number | null;
          used_count?: number;
          max_uses_per_user?: number | null;
          is_active?: boolean;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          code?: string;
          discount_type?: "percentage" | "fixed_amount";
          discount_value?: number;
          min_order_amount?: number | null;
          max_uses?: number | null;
          used_count?: number;
          max_uses_per_user?: number | null;
          is_active?: boolean;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      user_role: "customer" | "admin" | "super_admin";
      address_type: "shipping" | "billing";
      book_status: "draft" | "uploading" | "generating" | "preview_ready" | "ordered" | "printing" | "quality_check" | "packed" | "shipped" | "delivered" | "archived";
      order_status: "pending" | "confirmed" | "processing" | "shipped" | "delivered" | "cancelled" | "refunded";
      job_type: "upload_images" | "generate_preview" | "generate_pdf" | "send_email" | "generate_thumbnail" | "sync_order";
      job_status: "pending" | "processing" | "completed" | "failed" | "cancelled";
      notification_channel: "email" | "in_app";
      notification_type: "order_confirmation" | "shipping_update" | "delivery_confirmation" | "promotional" | "job_failed";
      discount_type: "percentage" | "fixed_amount";
      destination_category: "Coastline" | "Mountains" | "Cities" | "Deserts" | "Backwaters" | "Atlantic";
    };
  };
}
